USE [master]
GO
/****** Object:  Database [Project_STA]    Script Date: 4/30/2024 1:58:05 AM ******/
CREATE DATABASE [Project_STA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Project_STA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Project_STA.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Project_STA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Project_STA_log.ldf' , SIZE = 466944KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Project_STA] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Project_STA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Project_STA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Project_STA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Project_STA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Project_STA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Project_STA] SET ARITHABORT OFF 
GO
ALTER DATABASE [Project_STA] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Project_STA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Project_STA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Project_STA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Project_STA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Project_STA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Project_STA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Project_STA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Project_STA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Project_STA] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Project_STA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Project_STA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Project_STA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Project_STA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Project_STA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Project_STA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Project_STA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Project_STA] SET RECOVERY FULL 
GO
ALTER DATABASE [Project_STA] SET  MULTI_USER 
GO
ALTER DATABASE [Project_STA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Project_STA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Project_STA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Project_STA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Project_STA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Project_STA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Project_STA', N'ON'
GO
ALTER DATABASE [Project_STA] SET QUERY_STORE = OFF
GO
USE [Project_STA]
GO
/****** Object:  Table [dbo].[Call_Charges]    Script Date: 4/30/2024 1:58:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Call_Charges](
	[CallType ] [varchar](255) NULL,
	[CallCharges_2018] [varchar](255) NULL,
	[CallCharges_2019] [varchar](255) NULL,
	[CallCharges_2020] [varchar](255) NULL,
	[CallCharges _2021] [varchar](255) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Call_Data]    Script Date: 4/30/2024 1:58:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Call_Data](
	[CallTimestamp] [varchar](255) NULL,
	[CallType] [varchar](255) NULL,
	[EmployeeID] [varchar](255) NULL,
	[CallDuration] [varchar](255) NULL,
	[WaitTime] [varchar](255) NULL,
	[CallAbandoned] [varchar](255) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Call_Types]    Script Date: 4/30/2024 1:58:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Call_Types](
	[CallTypeID] [varchar](255) NULL,
	[CallTypeLabel] [varchar](255) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employees]    Script Date: 4/30/2024 1:58:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employees](
	[EmployeeID] [varchar](255) NULL,
	[EmployeeName] [varchar](255) NULL,
	[Site] [varchar](255) NULL,
	[ManagerName] [varchar](255) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[US_States]    Script Date: 4/30/2024 1:58:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[US_States](
	[StateCD] [varchar](255) NULL,
	[Name] [varchar](255) NULL,
	[Region] [varchar](255) NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Project_STA] SET  READ_WRITE 
GO
