USE [master]
GO

/****** Object:  Database [Project_ODS]    Script Date: 01/05/2024 16:00:40 ******/
CREATE DATABASE [Project_ODS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Project_ODS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Project_ODS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Project_ODS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Project_ODS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Project_ODS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Project_ODS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Project_ODS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Project_ODS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Project_ODS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Project_ODS] SET ARITHABORT OFF 
GO

ALTER DATABASE [Project_ODS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Project_ODS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Project_ODS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Project_ODS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Project_ODS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Project_ODS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Project_ODS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Project_ODS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Project_ODS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Project_ODS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Project_ODS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Project_ODS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Project_ODS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Project_ODS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Project_ODS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Project_ODS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Project_ODS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Project_ODS] SET RECOVERY FULL 
GO

ALTER DATABASE [Project_ODS] SET  MULTI_USER 
GO

ALTER DATABASE [Project_ODS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Project_ODS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Project_ODS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Project_ODS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Project_ODS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Project_ODS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Project_ODS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Project_ODS] SET  READ_WRITE 
GO


USE [Project_ODS]
GO

/****** Object:  Table [dbo].[Employees]    Script Date: 01/05/2024 16:00:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Employees](
	[EmployeeID] [varchar](20) NULL,
	[EmployeeFirstName] [varchar](50) NULL,
	[EmployeeLastName] [varchar](50) NULL,
	[ManagerFirstName] [varchar](50) NULL,
	[ManagerLastName] [varchar](50) NULL,
	[SiteTown] [varchar](50) NULL,
	[State] [varchar](50) NULL,
	[Region] [varchar](50) NULL
) ON [PRIMARY]
GO